pipeline:
  build:
    image: g3rv4/blog-builder
    commands:
      # Store the current version so that it can be used on the blog
      - "echo `git rev-parse HEAD` > _data/version.json"

      # Replace local config settings with prod settings
      - "sed -i '/#local/d' _config.yml"
      - "sed -i 's/#prod://g' _config.yml"

      # Minify the CSS files and update them in the HTML
      - uglifycss public/css/poole.css public/css/syntax.css public/css/hyde.css > public/css/site.min.css
      - sed -i '/\.css/d' _includes/head.html
      - sed -i '/CSS -->/a   <link rel="stylesheet" href="{{ site.baseurl }}/public/css/site.min.css">' _includes/head.html

      # Build the blog!
      - "/root/.rbenv/shims/jekyll build"
      - "rm -rf /var/site-destination/*"
      - "cp -r _site/* /var/site-destination/"

      # Expire Cloudflare's cache
      - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/$${CLOUDFLARE_ZONE}/purge_cache\" -H \"X-Auth-Email: $${CLOUDFLARE_EMAIL}\" -H \"X-Auth-Key: $${CLOUDFLARE_KEY}\" -H \"Content-Type: application/json\" --data '{\"purge_everything\":true}'"
      - echo 'sleeping 30 seconds...'
      - sleep 30

      # hit all the routes
      - phantomjs --ignore-ssl-errors=true --ssl-protocol=any /var/building-scripts/force-cache.js $$(wget -O - https://d4tagirl.com/sitemap.xml | grep loc | sed 's/ *<loc>\(.*\)<\\\/loc>/\\1/' | sed ':a;N;$$!ba;s/\\\n/ /g')

    secrets: [cloudflare_zone, cloudflare_email, cloudflare_key]
    volumes:
      - /home/gervasio/docker/nginx/volumes/html/d4tagirl.com:/var/site-destination
      - /home/gervasio/building-scripts:/var/building-scripts
