---
layout: post
title:  Al estilo R-Ladies!
date: "2017-06-21 15:19:29 UYT"
published: true
tags: [r-ladies, comunidad, genero, inclusion, grupo de usuarios, r, rstats, español, es]
description: Mi experiencia con la comunidad de R-Ladies, un grupo genial de mujeres que construyeron un entorno verdaderamente inclusivo para mujeres en la comunidad de R.
---
Mi experiencia con la comunidad de R-Ladies, un grupo genial de mujeres que construyeron un entorno verdaderamente inclusivo, para que mujeres en la comunidad de R de todo el mundo alcancen su verdadero potencial.

<!--more-->
Hace ya unos meses escribí un [artículo en inglés de mi experiencia cuando me acerqué a la comunidad de R-Ladies]({% post_url 2017-01-27-the-r-ladies-way %}). Mi motivación en ese momento era difundir la comunidad y que más gente se acerque, así que acá está mi artículo en español con el objetivo de que el idioma no sea una barrera. Como se me acabó el repertorio de idiomas en los que puedo escribir (y transmitir lo que efectivamente quiero!), dejo la puerta abierta a que surjan voluntari@s para traducirlo a otras lenguas `r emo::ji("woman_shrugging_light_skin_tone")`

4 meses atrás renuncié a mi trabajo en una de las decisiones más valientes (y difíciles) de mi carrera. No es que nunca me haya visualizado como una persona que tiene un trabajo para toda la vida (para nada!), pero siempre he sido muy cautelosa con mis decisiones, pensando varios movimientos adelante. Hace alrededor de un año estaba en un cargo en Equifax que me gustaba y tenía mucha estabilidad. Como Analytics Consultant dedicaba la mayoría de mi tiempo a desarrollar modelos a medida de Credit Scoring, y la sensación de que necesitaba un cambio empezó a aparecer: no me sentía suficientemente desafiada y no estaba encontrando ninguna forma de motivarme. Tenía que hacer un cambio. Empecé a buscar trabajo, pero [Uruguay (donde vivo)](https://es.wikipedia.org/wiki/Uruguay) es un país muy chico donde las posiciones de Data Science no son tan comunes, así que las pocas cosas que fueron surgiendo no llevaron a ningún lado. Entonces decidí que iba a renunciar de todas formas y ver si podía volver a estar contenta y seguir mi viaje para convertirme en Data Scientist. Y lo hice.

Lo gracioso (y aterrador) era que no tenía idea de lo que iba a hacer después. Intentá explicarle a tus padres que estás tratando de *encontrarte* a los 33 años de edad... no es tan fácil! El único plan que tenía era enfocarme en capacitarme y en aprender a convivir y llevarme bien con la incertidumbre (no es que tuviera otra alternativa para esto último!).

Me tomé un par de semanas para estar más tranquila y después empecé a mirar qué estaba pasando en la comunidad de R. He usado R desde la Universidad, pero nunca había interactuado con la comunidad. Mi estrategia fue empezar a seguir gente interesante en Twitter (ni siquiera me acuerdo cómo supe a quién seguir), leer [R-Bloggers](https://www.r-bloggers.com/), y *hacer cosas* que parecían de alguna forma útiles o que me hicieran sentir realizada:

* ayudé a [traducir a español](https://github.com/BetaAndBit/ComicBooks/blob/master/es_la/HeavyDog_es_la.pdf) [un comic de introducción a R para estudiantes de secundaria](https://github.com/BetaAndBit/ComicBooks/blob/master/en/HeavyDog_en.pdf) 
* descubrí y apliqué al [programa NASA Datanauts 2017](https://open.nasa.gov/explore/datanauts/) 
* tomé clases de Machine Learning en la Maestría que estoy cursando
* aprendí a resolver un cubo de Rubik (bueno, la verdad es que lo Googleé! Y siempre quise aprender a hacerlo así que no me juzgues...) 

Si trabajaba duro y seguía mi intuición algo iba a salir. Incluso si no, iba a estar probando cosas nuevas y divirtiéndome. Esto sí que era un desafío!

De alguna forma empezaron a aparecer tweets de R-Ladies en mi timeline, y empecé a prestarles atención. Muchas de esas personas que me inspiraban y seguía en Twitter estaban vinculadas a esta organización, así que definitivamente era *algo*. Exactamente esa fue la razón por la que sentí que no iba a tener un lugar ahí: probablemente ya tuvieran todo resuelto (lo cual era cierto) y no creí que tuviera nada para contribuir (*este fue mi primer error*). Buscando un capítulo en Uruguay para empezar a ir a sus reuniones (capítulo es como se llama a cada grupo local), no encontré ninguno (como decía, es un país pequeño). Mi segundo intento fue Argentina, un país 12 veces más grande y a 3 horas de barco desde mi ciudad, pero no encontré ningún capítulo tampoco. Así que no hice nada (*segundo error*). Siempre fui un poco tímida cuando no conozco a nadie, así que no me sentí cómoda como para escribir igual y empezar a participar de la comunidad. Ni siquiera creo que se me haya cruzado por la cabeza.

Los primeros días de enero anunciaron el capítulo de Buenos Aires de R-Ladies (Argentina, buenísimo!), una forma genial de empezar mi año de no tener ni idea qué hacer! Y esta vez me anoté a [su grupo en Meetup](https://www.meetup.com/rladies-buenos-aires/) para participar de los encuentros. Les conté a las organizadoras mi situación y en dos días me convertí en co-organizadora de ese capítulo, con dos mujeres divinas que no conocía (*acá fue que empecé a ver que ésta era una forma mucho mejor de hacer las cosas* `r emo::ji("sweat_smile")` ). Enseguida me sentí incluida e inmediatamente empecé a encontrar cosas en las que podía contribuir, sin importar qué tan chiquitas parecían.

Tratando de ver cómo podía ayudar con el capítulo de Buenos Aires me di cuenta de que no sabía cómo funcionaban algunas cosas. Y esta vez sentí algo diferente: *no tuve miedo de preguntar*. Fue la primera vez que no tuve miedo de decir algo equivocado o preguntar algo obvio y ser ridiculizada. Ni siquiera sé si esto fue un efecto puramente de género, pero este grupo de mujeres tuvo tanta buena onda conmigo que nunca me sentí desubicada. Más bien todo lo contrario!

Ya estaba pensando en tener mi blog, y la sensación de que empezaba a ser *una de ellas* me dio el impulso extra que necesitaba. Como el inglés no es mi lengua nativa, tenía esa preocupación adicional. Antes de anunciar [mi primer artículo del blog]({% post_url 2017-01-23-what-demographics-voted-for-trump %}) tuve las sugerencias de varias R-Ladies. Gente que nunca hubiera esperado que me contactara me estaba dando su opinión, personas que eran como celebridades para mi! En el momento en que lo publiqué me sentí mucho más segura y relajada como para disfrutarlo `r emo::ji("smiley")` 

Las cosas empezaron a funcionar para mi: Me aceptaron para unirme a la [clase de Primavera de NASA Datanauts 2017](https://open.nasa.gov/blog/welcome-datanauts-2017-spring-class/) (despúes supe que fue el tweet de una R-Lady por el que me enteré que existía el programa) e incluso respondí algunas preguntas de Stack Overflow! Ésta era la clase de estímulo que precisaba para recuperar la confianza! Ahora estoy en busca de un trabajo genial! `r emo::ji("wink")`

Lo que estoy tratando de decir con todo esto es: sea que haya un capítulo en tu ciudad o no, sin importar tu grado de timidez, hay un grupo genial de mujeres listas para proporcionarte la contención que necesitás para alcanzar tu potencial. Algunas de ellas probablemente estén en una situación similar a la tuya, así que también es un lugar para compartir experiencias y no sentirte sola.

Todavía no te decidís? Podés:

* [Mencionarme en Twitter](https://twitter.com/intent/tweet?user_id=114258616)
* Escribir a info@rladies.org (o sentite libre de escribirme dani@rladies.org)
* Seguirnos en Twitter: [@RLadiesGlobal](https://twitter.com/intent/user?screen_name=RLadiesGlobal)

Si solamente estás curios@ podés visitar: [http://www.rladies.org](http://www.rladies.org)

