---
layout: post
title:  Hello World!
date: "2016-12-30 19:13:22 UYT"
published: true
tags: ['something']
---
holas

<!--more-->
Hi! I'm Daniela and I've been working in Data Science for the last 4 years. I am an Economist from Uruguay (South America) and this is my first blog post *ever* so I'll be doing a lot of experimenting while sharing my personal projects in the Data Science field. I'm a bit nervous (and a lot excited!) about it. 

There is a "Hello World" here to help me overcome my fear of writing for an audience, in a foreign language, to finally give way to my more productive articles (this very post took me 3 days of writing!).

Up until now I have only had my Facebook account for friends and my Twitter account mostly as a news feed. Of course I've never shared any of the things I've done with the community (I guess I am not that confident?). From there to start blogging there is a lot of work to be done, but I'm ready now! Since I've been benefiting from the knowledge of many people over the world all this time, I would be thrilled if some of you found any of the things I do helpful (or at least enjoyable) in return.

I hope you find stuff here you like, leave your comments and enjoy your visit :)  