<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 
			
  
    <meta name="twitter:card" content="summary"/>
    
      <meta name="twitter:image" content="/images/avatar.png" />
    
  
  
  <meta name="twitter:title" content="Using Rpart to figure out who voted for Trump"/>
  <meta name="twitter:description" content="I examine the characteristics of the population that made Donald Trump the 45th President of the United States. Through Machine Learning algorithm CART I analize the Election Results by county."/>
  
    <meta name="twitter:site" content="@your_twitter_id"/>
  
  
  
  
    <meta name="twitter:creator" content="@site_author"/>
  



		
		<meta name="author" content="site_author">
		<meta name="description" content="Site Description">
		<meta name="generator" content="Hugo 0.59.1" />
		<title>Using Rpart to figure out who voted for Trump &middot; d4tagirl</title>
		<link rel="shortcut icon" href="/images/favicon.ico">
		<link rel="stylesheet" href="/css/style.css">
		<link rel="stylesheet" href="/css/highlight.css">

		
		<link rel="stylesheet" href="/css/font-awesome.min.css">
		

		
		<link href="/index.xml" rel="alternate" type="application/rss+xml" title="d4tagirl" />
		

		
	</head>

    <body>
       <nav class="main-nav">
	
	
		<a href='/'> <span class="arrow">←</span>Home</a>
	
	<a href='/posts'>Archive</a>
	<a href='/tags'>Tags</a>
	<a href='/about'>About</a>

	

	
	<a class="cta" href="/index.xml">Subscribe</a>
	
</nav>


        <section id="wrapper" class="post">
            <article>
                <header>
                    <h1>
                        Using Rpart to figure out who voted for Trump
                    </h1>
                    <h2 class="headline">
                    Jan 1, 0001 00:00
                    · 3511 words
                    · 17 minute read
                      <span class="tags">
                      
                      
                          
                              <a href="/tags/rstats">rstats</a>
                          
                              <a href="/tags/r">r</a>
                          
                              <a href="/tags/machine-learning">Machine Learning</a>
                          
                              <a href="/tags/rpart">rpart</a>
                          
                              <a href="/tags/cart">CART</a>
                          
                              <a href="/tags/tidyverse">tidyverse</a>
                          
                              <a href="/tags/unbalanced-classes">unbalanced classes</a>
                          
                      
                      
                      </span>
                    </h2>
                </header>
                
                  
                    <div id="toc">
                      <nav id="TableOfContents">
<ul>
<li><a href="#the-data">The data</a></li>
<li><a href="#building-the-response-variable">Building the Response Variable</a></li>
<li><a href="#some-visualization-about-race-and-origin">Some visualization about race and origin</a></li>
<li><a href="#the-classification-tree">The Classification Tree</a>
<ul>
<li><a href="#growing-the-tree">Growing the tree</a></li>
<li><a href="#pruning-the-tree">Pruning the tree</a></li>
</ul></li>
<li><a href="#performance-evaluation">Performance Evaluation</a>
<ul>
<li><a href="#missclassification-error">Missclassification Error</a></li>
<li><a href="#kappa-statistic">Kappa statistic</a></li>
<li><a href="#roc-curve-and-auroc">ROC Curve and AUROC</a></li>
</ul></li>
<li><a href="#warning-about-classification-trees-instability">Warning about Classification Trees instability</a>
<ul>
<li><a href="#k-fold-cross-validation-for-model-accuracy-estimation">K-fold Cross Validation for model accuracy estimation</a></li>
</ul></li>
<li><a href="#variable-importance">Variable Importance</a></li>
<li><a href="#what-now">What now?</a></li>
</ul>
</nav>
                    </div>
                  
                
                <section id="post-body">
                    <p>I examine the characteristics of the population that made Donald Trump the 45th President of the United States. Through Machine Learning algorithm CART I analize the Election Results by county.</p>

<p>It&rsquo;s been a few days since we witnessed the inauguration of Donald Trump as the 45th President of the United States, whose victory over Hillary Clinton came as a shock for most people. I&rsquo;m not much into politics (and it is not even my country!) but this result really caught my attention, so I wanted to dig a little about the population&rsquo;s characteristics that made him the winner of the Election.</p>

<p>I&rsquo;ve been studying Machine Learning for a while now, and a couple of months ago I discovered the <em>awesome</em> <code>tidyverse</code> world (I can&rsquo;t believe the way I used to do things :$), so I thought this was a great opportunity to test my skills. In addition to that, I&rsquo;m not a native English speaker so in this first post I am facing major challenges! If you see something improvable, not clear or plainly wrong, please leave a comment or <a href="https://twitter.com/intent/tweet?user_id=114258616">mention me on Twitter</a>.</p>

<p>What I do here is estimate a Classification Tree (CART) to find an association between the winner in the county and its socio-demographic characteristics.</p>

<h1 id="the-data">The data</h1>

<p>I recently joined Kaggle, and <a href="https://www.kaggle.com/joelwilson">Joel Wilson</a> gathered data about <em>2016 US Election Results</em> by county and <em>County Quick Facts</em> from the <em>US Census Bureau</em>. <a href="https://www.kaggle.com/joelwilson/2012-2016-presidential-elections">This is the data</a> I use to run this analysis.</p>

<p>I start by loading the data and merging it. No mystery here, except I load it using <code>readr</code> and merge it using <code>dplyr</code> (yay!).</p>

<pre><code class="language-r">library(readr)
library(dplyr)

url_pop &lt;- 'https://github.com/d4tagirl/TrumpVsClintonCountiesRpart/raw/master/data/county_facts.csv'
url_results &lt;- 'https://github.com/d4tagirl/TrumpVsClintonCountiesRpart/raw/master/data/US_County_Level_Presidential_Results_12-16.csv'  
pop &lt;- read_csv(url(url_pop))
results &lt;- read_csv(url(url_results))

votes &lt;- results %&gt;% 
  inner_join(pop, by = c(&quot;combined_fips&quot; = &quot;fips&quot;))
</code></pre>

<p>It is a clean dataset, but I need to do some modifications for the analysis:</p>

<ul>
<li>There is no election data for the state of Alaska so I remove those counties.</li>
<li>Replace the old ID (<code>X1</code>) with a new one (<code>ID</code>).</li>
<li>Delete non relevant variables.</li>
<li>Rename variables to make them interpretable.</li>
</ul>

<p>All of this taking advantage of the <code>dplyr</code> of course.</p>

<pre><code class="language-r">votes &lt;- votes %&gt;%
  filter(state_abbr != &quot;AK&quot;) %&gt;%
  mutate(ID = rank(X1)) %&gt;%
  select(-X1, -POP010210, -PST040210, -NES010213, -WTN220207) %&gt;%
  rename(age18minus = AGE295214, age5minus = AGE135214, age65plus = AGE775214,
    american_indian = RHI325214, asian = RHI425214, asian_Firms = SBO215207,
    black = RHI225214, black_firms = SBO315207, building_permits = BPS030214,
    density = POP060210, edu_batchelors = EDU685213, edu_highschool = EDU635213,
    firms_num = SBO001207, foreign = POP645213, hisp_latin = RHI725214,
    hispanic_firms = SBO415207, home_owners_rate = HSG445213, households = HSD410213,
    housing_Units = HSG010214, housing_units_multistruct = HSG096213, income = INC910213,
    land_area = LND110210, living_same_house_12m = POP715213, manuf_ship = MAN450207,
    Med_house_income = INC110213, Med_val_own_occup = HSG495213, native_haw = RHI525214,
    native_firms = SBO115207, nonenglish = POP815213, pacific_isl_firms = SBO515207,
    pers_per_household = HSD310213, pop_change = PST120214, pop2014 = PST045214,
    poverty = PVY020213, priv_nofarm_employ = BZA110213, priv_nonfarm_employ_change = BZA115213,
    priv_nonfarm_estab = BZA010213, retail_sales = RTN130207, retail_sales_percap = RTN131207,
    sales_accomod_food = AFN120207, sex_f = SEX255214, travel_time_commute = LFE305213,
    two_races_plus = RHI625214, veterans = VET605213, white = RHI125214, white_alone = RHI825214,
    women_firms = SBO015207,
    Trump = per_gop_2016, Clinton = per_dem_2016, Romney = per_gop_2012, Obama = per_dem_2012)
</code></pre>

<p>Most of these variables are measured as a percentage of people in the county with that characteristic (e.g. <code>edu_batchelors</code> and <code>black</code>), or the total amount in the county (e.g. <code>land_area</code> and <code>firms_num</code>).</p>

<p>Note that there is a <code>white</code> variable and a <code>white_alone</code> variable. This is because there are 2 separate facts gathered here.</p>

<ul>
<li><p><code>white</code> refers to <em>race</em>: <em>people having origins in any of the original peoples of Europe, the Middle East, or North Africa</em>. If a person declares <em>white</em> among other races, is classified as <code>two_races_plus</code> and not as <code>white</code>.</p></li>

<li><p><code>white_alone</code> refers to <em>white race</em> people who also reported <em>not Hispanic or Latino origin</em>.</p></li>
</ul>

<p>For further references on any variable you can <a href="https://www.census.gov/quickfacts/fact/table/US/PST045218">go to the Census Bureau&rsquo;s site</a>.</p>

<h1 id="building-the-response-variable">Building the Response Variable</h1>

<p>I create the variable I want to explain: <code>pref_cand_T</code>. It takes the value <code>1</code> if <code>Trump</code> has a greater percentage of votes than <code>Clinton</code> in the county, and <code>0</code> otherwise. Note that it is not necessary that one of them has more than 50% of the votes, it&rsquo;s only required that has more votes than the other.</p>

<pre><code class="language-r">votes &lt;- votes %&gt;% mutate(pref_cand_T = factor(ifelse(Trump &gt; Clinton, 1, 0)))

summary &lt;- votes %&gt;% summarize(Trump       = sum(pref_cand_T == 1),
                               Clinton     = n() - Trump,
                               Trump_per   = mean(pref_cand_T == 1),
                               Clinton_per = 1 - Trump_per)

library(knitr)
knitr::kable(summary, align = 'l')
</code></pre>

<table>
<thead>
<tr>
<th align="left">Trump</th>
<th align="left">Clinton</th>
<th align="left">Trump_per</th>
<th align="left">Clinton_per</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">2624</td>
<td align="left">488</td>
<td align="left">0.8431877</td>
<td align="left">0.1568123</td>
</tr>
</tbody>
</table>

<p>Trump got more votes than Clinton in 2624 counties opposing the 488 other counties where Clinton got more votes (remember we are talking about counties and not Electoral College votes). The proportion is 84% for Trump and 16% for Clinton.</p>

<h1 id="some-visualization-about-race-and-origin">Some visualization about race and origin</h1>

<p>I explore briefly some counties&rsquo; characteristics about <em>race</em> and <em>origin</em> by visualizing them. It is time to test my brand new <code>ggplot</code> skills!</p>

<p>I generate a plot for the mean of each characteristic across all counties, which is the mean of the proportion of people with each characteristic in all counties (simple mean, without considering the population of the county).</p>

<pre><code class="language-r">library(tidyr)
library(ggplot2)

# Order in x-axis
limits = c(&quot;white&quot;, &quot;white_alone&quot;, &quot;black&quot;, &quot;asian&quot;, &quot;hisp_latin&quot;, &quot;foreign&quot;)

total &lt;- votes %&gt;% 
  summarize(
    white       = mean(white),
    white_alone = mean(white_alone),
    black       = mean(black),
    asian       = mean(asian),
    hisp_latin  = mean(hisp_latin),
    foreign     = mean(foreign)) %&gt;%
  gather(variable, value) %&gt;% 
  ggplot() +
  geom_bar(aes(x = variable, y = value), 
           stat = 'identity', width = .7, fill = &quot;#C9C9C9&quot;) +
  geom_vline(xintercept = c(4.5, 5.5), alpha = 0.2 ) +
  scale_x_discrete(limits = limits) +
  labs(title = &quot;Mean of % in counties&quot;,    
       subtitle = &quot;(Simple mean of % in counties without considering counties' population)&quot;) +
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(),
        axis.text.x = element_blank(), axis.line = element_line(colour = &quot;grey&quot;),
        panel.grid.major = element_blank(), panel.border = element_blank())
</code></pre>

<p>Something beautiful about <code>tidyverse</code> is the way that you can build up the solution. The first part is simply <code>dplyr</code> plus <code>tidyr::gather</code>, necessary to manipulate the input for the <code>ggplot</code>. The rest is the <code>ggplot</code> layer by layer.</p>

<p>It seems like a lot of code for a simple plot, but trust me: once you get the hang of <code>ggplot</code>, it is magic! The only fear is that you&rsquo;ll want to customize <em>everything</em>! (An that&rsquo;s why I have so much code&hellip;)</p>

<p>Then I generate the same plot by candidate.</p>

<pre><code class="language-r">by_candidate &lt;- votes %&gt;% 
  group_by(pref_cand_T) %&gt;% 
  summarize(
    white       = mean(white),
    white_alone = mean(white_alone),
    black       = mean(black),
    asian       = mean(asian),
    hisp_latin  = mean(hisp_latin),
    foreign     = mean(foreign)) %&gt;% 
  gather(variable, value, -pref_cand_T) %&gt;% 
  ggplot() + 
  geom_bar(aes(x = variable, y = value, fill = pref_cand_T),
           stat = 'identity', position = 'dodge') + 
  geom_vline(xintercept = c(4.5, 5.5), alpha = 0.2 ) +
  scale_fill_manual(values = alpha(c(&quot;blue&quot;, &quot;red&quot;)), 
                    breaks = c(&quot;0&quot;, &quot;1&quot;), labels = c(&quot;Clinton&quot;, &quot;Trump&quot;)) +
  scale_x_discrete(limits = limits) +
  labs(fill = &quot;winner&quot;) +
  theme_bw() +
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(),
        axis.line = element_line(colour = &quot;grey&quot;), legend.position = &quot;bottom&quot;, 
        panel.grid.major = element_blank(), panel.border = element_blank())
</code></pre>

<p>Same as before, but excluding the grouping variable <code>pref_cand_T</code> from the gathering to generate the <code>ggplot</code> input.</p>

<p>Next I plot both. I use the <code>gridExtra</code> package to display both plots together. (And yes, it was a lot of learning this past few months!).</p>

<pre><code class="language-r">library(gridExtra)

grid.arrange(total, by_candidate, nrow = 2)
</code></pre>

<p><img src="/figure/source/what-demographics-voted-for-trump/2017-01-23-what-demographics-voted-for-trump/plot_race-1.png" title="plot of chunk plot_race" alt="plot of chunk plot_race" style="display: block; margin: auto;" /></p>

<p>Among races, the mean of <em>white</em> people is higher for the counties where Trump won than the rest, and for the counties where Clinton won, the mean of <em>black</em> and <em>asian</em> people is higher. Clinton also won in counties with higher mean of <em>Hispanic or Latin origin</em> people, and <em>foreign-born</em> population.</p>

<p>In a future post I will be doing some more digging into this variables to find out more.</p>

<h1 id="the-classification-tree">The Classification Tree</h1>

<p>As a standard practice, I split the data into <code>train</code> and <code>test</code> samples. I use 70% of the counties for training and the rest for testing. Since I am dealing with unbalanced data, I use the <code>createDataPartition</code> function in the <code>caret</code> package that conserves the proportion of classes across all samples.</p>

<pre><code class="language-r">library(caret)

perc_train &lt;- 0.7
set.seed(3333)

trainIndex &lt;- createDataPartition(y = votes$pref_cand_T, p = perc_train,
                                  list = FALSE, times = 1)

train &lt;- votes %&gt;% subset(ID %in% trainIndex)
test &lt;-  votes %&gt;% setdiff(train)
</code></pre>

<h2 id="growing-the-tree">Growing the tree</h2>

<p>I estimate the tree using <code>rpart</code>, excluding variables non relevant for modelling, and those used to build the response variable.</p>

<pre><code class="language-r">library(rpart)

pref_cand_rpart &lt;- rpart(pref_cand_T ~ .,
                         data = train[, -c(1:24, 70)],
                         control = rpart.control(xval = 10, cp = 0.0001))
</code></pre>

<p>This algorithm grows a tree from a root that has all the observations, splitting binarily to reduce the impurity of its nodes, until some stopping rule is met. I set up this rules with the <code>rpart.control</code>:</p>

<ul>
<li><code>minsplit = 20</code> is the default, the minimum of observations in a node to attempt a split.</li>
<li><code>minbucket = 7</code> is also the default, the minimum of observations in any terminal node.</li>
<li><code>cp = 0.0001</code> is the minimum factor of decreasing lack of fit for a split to be attempted.</li>
</ul>

<p>This is quite a big tree because I use a very small <code>cp</code> (I&rsquo;m not showing it for that reason, but you can <a href="/figure/source/what-demographics-voted-for-trump/2017-01-23-what-demographics-voted-for-trump/plot_large_tree-1.png">find it here</a>{:target=&rdquo;_blank&rdquo;}). Simpler trees are preferred, since they are less likely to overfit the data.</p>

<h2 id="pruning-the-tree">Pruning the tree</h2>

<p>Now it&rsquo;s time to prune the tree. To do this, I keep the split if it meets some criteria about the balance between the impurity reduction (<em>cost</em>) and the increase of size (<em>complexity</em>). This is the <code>cp</code>.</p>

<p>I am pruning the tree following the 1-SE rule, according to which I choose the simplest model with accuracy similar to the best model.</p>

<pre><code class="language-r">library(tibble)
cp &lt;- as_tibble(pref_cand_rpart$cptable) %&gt;%
  filter(xerror &lt;= min(xerror) + xstd) %&gt;%
  filter(xerror == max(xerror)) %&gt;%
  select(CP) %&gt;%
  unlist()

winner_rpart &lt;- prune(pref_cand_rpart, cp = cp)
</code></pre>

<p><code>dplyr</code> manipulates <code>dataframes</code>, so I use the <code>tibble::as_tibble</code> function to convert the <code>pref_cand_rpart$cptable</code> table to a <code>tibble</code>, and then select the <code>cp</code>.</p>

<p>And here I have the tree! (If you know some other way to plot nicer trees, please comment!)</p>

<pre><code class="language-r">library(rpart.plot)

rpart.plot(winner_rpart, main = &quot;Winner candidate in county&quot;,
           extra = 104, split.suffix = &quot;%?&quot;, branch = 1,
           fallen.leaves = FALSE, box.palette = &quot;BuRd&quot;,
           branch.lty = 3, split.cex = 1.2,
           shadow.col = &quot;gray&quot;, shadow.offset = 0.2)
</code></pre>

<p><img src="/figure/source/what-demographics-voted-for-trump/2017-01-23-what-demographics-voted-for-trump/plot_pruned_tree-1.png" title="plot of chunk plot_pruned_tree" alt="plot of chunk plot_pruned_tree" style="display: block; margin: auto;" /></p>

<p>Starting from the top (the root), the tree splits the population in two subsets according to the question asked (the variable and the cut), and it does the same for every node. If the county meets the criteria it is classified to the left, and otherwise to the right. In this case the first split indicates that if the county has less than 50% <code>white_alone</code> population, it is classified to the left node (only 12% of the counties), and the rest goes to the right (80% of the counties). The higher the percentage of counties that Trump won in the node, the redder the node. Nodes associated with Clinton are bluer.</p>

<p>Apparently <em>race</em> is one of the most important characteristic determining the winner candidate. 3 over the 5 splits include race (we will know more about this when we check the <em>Variable Importance</em> later on). And there is also a variable referring the <em>housing structure</em> and other about <em>education</em>.</p>

<p>One key feature of CART is that it allows different characteristics to be relevant for each node resulted from a split. In this case, for counties with less than 50% <code>white_alone</code> population, the winner was also determined by the amount of housing units in multi-unit structures (maybe an urbanization&rsquo;s proxy?) and the percentage of 25 years old or older persons holding a Bachelor&rsquo;s degree or higher. But for the rest of the counties, it was determined by other racial characteristics. This is because the algorithm partitions the feature space in two using linear parallel to the axis decision boundaries, and for each generated region does the same, over and over.</p>

<p>This can be revealing, uncovering underlying interactions of variables for different groups, harder to discover using other methods.</p>

<h1 id="performance-evaluation">Performance Evaluation</h1>

<p>Now I evaluate how good this model is. Prior to this post I wouldn&rsquo;t pay any extra attention to the usage of different measures taking into account how unbalanced the data was. There are a lot of measures to evaluate the fit, I will explore some of them prioritizing the ones that explicitly deal with unbalanced classes.</p>

<p>This evaluations should always be done over the <code>test</code> sample, otherwise it would be like cheating!</p>

<h2 id="missclassification-error">Missclassification Error</h2>

<p>One classic way to evaluate the performance of a classifier is by calculating the <em>missclassification error</em>, simply by computing the percentage of times that the the classifier is wrong.</p>

<pre><code class="language-r">test &lt;- test %&gt;%
  mutate(pred = predict(winner_rpart, type = &quot;class&quot;, test),
         pred_prob_T = predict(winner_rpart, type = &quot;prob&quot;, test)[,2],
         error = ifelse(pred != pref_cand_T, 1, 0))

missc_error &lt;- test %&gt;% summarize(missc_error = mean(error))
knitr::kable(missc_error, align = 'l')
</code></pre>

<table>
<thead>
<tr>
<th align="left">missc_error</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">0.0782422</td>
</tr>
</tbody>
</table>

<p>But since I&rsquo;ve been doing my research, it has become clear that in this case I could not treat this measure without further considerations.</p>

<p>Let&rsquo;s suppose I have a model that predicts for all cases Trump as the winner. It would have a missclassification error of 15%, <em>not so bad!</em> But it is definitely not a great model: it would be 100% accurate for predicting counties where Trump won, but it would be wrong for <em>all</em> of the counties where Clinton won. This is known as the <em>Accuracy Paradox</em>, and that is why we need some alternatives to measure how good is this tree in predicting the county&rsquo;s winner.</p>

<h2 id="kappa-statistic">Kappa statistic</h2>

<p>One good thing to do in any case (balanced the data or not) is to take a look at the confusion matrix. This is the input for many performance measures as shown next.</p>

<pre><code class="language-r">test %&gt;%
  select(pred, pref_cand_T) %&gt;%
  table() %&gt;%
  confusionMatrix()
</code></pre>

<pre><code>## Confusion Matrix and Statistics
## 
##     pref_cand_T
## pred   0   1
##    0  87  14
##    1  59 773
##                                           
##                Accuracy : 0.9218          
##                  95% CI : (0.9026, 0.9382)
##     No Information Rate : 0.8435          
##     P-Value [Acc &gt; NIR] : 6.196e-13       
##                                           
##                   Kappa : 0.6611          
##  Mcnemar's Test P-Value : 2.607e-07       
##                                           
##             Sensitivity : 0.59589         
##             Specificity : 0.98221         
##          Pos Pred Value : 0.86139         
##          Neg Pred Value : 0.92909         
##              Prevalence : 0.15648         
##          Detection Rate : 0.09325         
##    Detection Prevalence : 0.10825         
##       Balanced Accuracy : 0.78905         
##                                           
##        'Positive' Class : 0               
## 
</code></pre>

<p>Just looking into this matrix we can have some clues on how good is the classifier for each class. Particularly I want to look closer at the <code>Kappa</code> statistic, because it specifically considers the unbalance between classes.</p>

<p><code>Kappa</code> measures the accuracy of the classifier <em>corrected by the probability of agreement by chance</em>. There is not much consensus on the magnitude of <code>Kappa</code> to consider it low or high, but it can be interpreted as how separate it is the obtained result from chance. In this case the <em>expected accuracy</em> (the one that occurs by chance) is 77% and the perfect accuracy is of course 100%. There is a gap of 23%, and this classifier closes this gap by 66% of it (15% of improvement!). The higher the <code>Kappa</code>, the better. Some sustain that a value of <code>Kappa</code> larger than 60% means a good agreement, so we are OK!</p>

<h2 id="roc-curve-and-auroc">ROC Curve and AUROC</h2>

<p>To complement the performance evaluation, I check the <code>ROC curve</code>. It plots the <em>True Positive Rate</em> against the <em>False Positive Rate</em> across many different thresholds of predicted probability. As we are evaluating a tree with only 6 final nodes, there is a limited amount of thresholds. (Trying to simplify this explanation, I came across <a href="https://www.dataschool.io/roc-curves-and-auc-explained/">this video</a> that is very clear if you want to go deeper)</p>

<p>This measure is great for classification analysis, and it is particularly useful here because it is not affected by unbalanced classes. Luckily I came across this great <code>ggplot2</code> extension, <code>plotROC</code>, and now I can use my favorite tools to create a pretty nice plot!</p>

<pre><code class="language-r">library(plotROC)

roc &lt;- test %&gt;%
  select(pref_cand_T, pred_prob_T) %&gt;%
  mutate(pref_cand_T = as.numeric(pref_cand_T) - 1,
         pref_cand_T.str = c(&quot;Clinton&quot;, &quot;Trump&quot;)[pref_cand_T + 1]) %&gt;%
  ggplot(aes(d = pref_cand_T, m = pred_prob_T)) +
  geom_roc(labels = FALSE)

roc +
style_roc(theme = theme_bw, xlab = &quot;False Positive Rate&quot;, ylab = &quot;True Positive Rate&quot;) +
theme(panel.grid.major = element_blank(), panel.border = element_blank(),
      axis.line = element_line(colour = &quot;grey&quot;)) +
ggtitle(&quot;ROC Curve for winner_rpart classifier&quot;) +
annotate(&quot;text&quot;, x = .75, y = .25,
         label = paste(&quot;AUROC =&quot;, round(calc_auc(roc)$AUC, 2)))
</code></pre>

<p><img src="/figure/source/what-demographics-voted-for-trump/2017-01-23-what-demographics-voted-for-trump/roc_curve-1.png" title="plot of chunk roc_curve" alt="plot of chunk roc_curve" style="display: block; margin: auto;" /></p>

<p>The <code>AUROC</code> (*A*rea *U*nder the <em>ROC</em> curve) computes the probability that the classifier ranks higher a positive instance than a negative one.</p>

<h1 id="warning-about-classification-trees-instability">Warning about Classification Trees instability</h1>

<p>When you use this kind of Machine Learning algorithm you should be aware that small changes in the data can change the tree. Find below a second tree generated by using the same parameters than before, but changing the seed to do the sampling.</p>

<pre><code class="language-r">set.seed(4444)

trainIndex_2 &lt;- createDataPartition(y = votes$pref_cand_T, p = perc_train,
                                    list = FALSE, times = 1)

train_2 &lt;- votes %&gt;% subset(ID %in% trainIndex_2)
test_2 &lt;-  votes %&gt;% setdiff(train_2)

winner_rpart_2 &lt;- rpart(pref_cand_T ~ .,
                         data = train_2[, -c(1:24, 70)],
                         control = rpart.control(xval = 10, cp = cp))

rpart.plot(winner_rpart_2, main = &quot;Winner candidate in county&quot;,
           extra = 104, split.suffix = &quot;%?&quot;, branch = 1,
           fallen.leaves = FALSE, box.palette = &quot;BuRd&quot;,
           branch.lty = 3, split.cex = 1.2,
           shadow.col = &quot;gray&quot;, shadow.offset = 0.2)
</code></pre>

<p><img src="/figure/source/what-demographics-voted-for-trump/2017-01-23-what-demographics-voted-for-trump/second_tree-1.png" title="plot of chunk second_tree" alt="plot of chunk second_tree" style="display: block; margin: auto;" /></p>

<p>Although it is not completely different, it changes a bit.</p>

<p>You can fight this using some ensemble method such as <em>Bagging</em>, <em>Random Forest</em> or <em>Boosting</em>, but as I&rsquo;m particularly interested in easily visualizing the decision rules and potentially finding different patterns for different groups, I find this method a better fit for this particular problem.</p>

<p>Since this algorithm is very sensitive to the <code>train</code> and <code>test</code> partition, I&rsquo;m interested in having an estimation of the <em>accuracy</em> for <em>this kind of specification of the tree</em> and not only for the specific one I found. This can be achieved by the K-fold Cross-Validation.</p>

<h2 id="k-fold-cross-validation-for-model-accuracy-estimation">K-fold Cross Validation for model accuracy estimation</h2>

<p>This method divides randomly the data into <code>k</code> equally sized subsets called <em>folds</em>. A tree is estimated in <code>k-1</code> of them and the performance is evaluated in the fold left behind. This is made <code>k</code> times, until each fold is used for validation exactly one time.</p>

<p>This was a non a straightforward thing for me to do. I wanted the <code>caret</code> package to calculate the K-fold Cross Validation accuracy estimation, but apparently most people use <code>caret::train</code> to find the parameter <code>cp</code> at the same time. I just wanted to estimate the accuracy associated with an already specified model (I&rsquo;ve already estimated the <code>cp</code>). Finally I found the way, specifying <code>tuneGrid = expand.grid(cp = cp)</code>.</p>

<pre><code class="language-r">tc &lt;- trainControl(&quot;cv&quot;, number = 10)
rpart.grid &lt;- expand.grid(cp = cp)
train.rpart &lt;- train(pref_cand_T ~ .,
                     data = votes[,-c(1:24, 70)], method = &quot;rpart&quot;,
                     trControl = tc,  tuneGrid = rpart.grid)

knitr::kable(train.rpart$results, align = &quot;l&quot;)
</code></pre>

<table>
<thead>
<tr>
<th align="left">cp</th>
<th align="left">Accuracy</th>
<th align="left">Kappa</th>
<th align="left">AccuracySD</th>
<th align="left">KappaSD</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">0.0380117</td>
<td align="left">0.9222377</td>
<td align="left">0.6869</td>
<td align="left">0.0111048</td>
<td align="left">0.0525811</td>
</tr>
</tbody>
</table>

<p>The <code>Kappa</code> statistic is now 0.69 (it was also 0.66 for the <code>winner_rpart</code>), with a 0.05 standard deviation. Again: good results!</p>

<h1 id="variable-importance">Variable Importance</h1>

<p>One last thing to check is the <em>Variable Importance</em>. CART is a <em>greedy</em> algorithm, meaning that it chooses the best split at each node without any consideration of the potential benefit on the overall tree performance of choosing a different one. This way it is possible to end up with a tree with some <em>apparently relevant</em> variables missing.</p>

<p>The <em>Variable Importance</em> in <code>rpart</code> is calculated not only taking into account the goodness of the split for variables that are actually in the tree, but also for the <code>surrogate</code> variables (the variables used in case the main variable is missing for an observation). We can see next that there are many more variables than in the original tree.</p>

<pre><code class="language-r">winner_rpart$variable.importance %&gt;%
  data_frame(variable = names(.), importance = .) %&gt;%
  mutate(importance = importance / sum(importance)) %&gt;%
  top_n(20) %&gt;%
  ggplot(aes(x = importance,
             y = reorder(variable, importance))) +
  geom_point() +
  labs(title = &quot;Importance of county characteristics \n in determining the most voted candidate&quot;,
       subtitle = &quot;(20 most relevant, Rpart, scaled to sum 1)&quot;) +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.line = element_line(colour = &quot;grey&quot;),
        panel.grid.major = element_blank(), panel.border = element_blank()) +
  geom_segment(aes(x = -Inf, y = reorder(variable, importance),
                   xend = importance, yend = reorder(variable, importance)),
               size = 0.2)
</code></pre>

<p><img src="/figure/source/what-demographics-voted-for-trump/2017-01-23-what-demographics-voted-for-trump/variable_importance-1.png" title="plot of chunk variable_importance" alt="plot of chunk variable_importance" style="display: block; margin: auto;" /></p>

<p>The most relevant characteristic is <code>white_alone</code>, the percentage of <em>white</em> population with <em>no Hispanic or Latin origin</em>. In the top 7 almost every characteristic is about race or origin, so it is probably one of the key aspects to study if we want to understand this phenomenon (no surprises here).</p>

<h1 id="what-now">What now?</h1>

<p>This was my first approach to the subject, I am already doing some extra analysis on the <em>race</em> phenomenon, so I&rsquo;ll be probably posting more on this soon.</p>

<p>If you made it until here: <strong>thank you!</strong> I tried to keep it simple and intuitive, covering all relevant aspects when estimating this kind of models. The R Markdown I used to generate this post is <a href="https://github.com/d4tagirl/d4tagirl.com/blob/master/_source/what-demographics-voted-for-trump/2017-01-23-what-demographics-voted-for-trump.Rmd">available here</a>.</p>

<p>If you see room for improvement or simply want to share something, please let me know by leaving your comments here or <a href="https://twitter.com/intent/tweet?user_id=114258616">mentioning me on Twitter</a> :)</p>
                </section>
            </article>

            
                <a class="twitter" href="https://twitter.com/intent/tweet?text=%2f1%2f01%2fusing-rpart-to-figure-out-who-voted-for-trump%2f - Using%20Rpart%20to%20figure%20out%20who%20voted%20for%20Trump by @your_twitter_id"><span class="icon-twitter"> tweet</span></a>

<a class="facebook" href="#" onclick="
    window.open(
      'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href),
      'facebook-share-dialog',
      'width=626,height=436');
    return false;"><span class="icon-facebook-rect"> Share</span>
</a>

            

            
                <div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'your_disqus_short_name'; 

     
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>

            

            

            <footer id="footer">
    
        <div id="social">

	
	
    <a class="symbol" href="https://www.github.com/nodejh">
        <i class="fa fa-github-square"></i>
    </a>
    
    <a class="symbol" href="https://www.twitter.com/nodejh">
        <i class="fa fa-twitter-square"></i>
    </a>
    


</div>

    
    <p class="small">
    
       © Copyright 2019 <i class="fa fa-heart" aria-hidden="true"></i> site_author
    
    </p>
    <p class="small">
        Powered by <a href="http://www.gohugo.io/">Hugo</a> Theme By <a href="https://github.com/nodejh/hugo-theme-cactus-plus">nodejh</a>
    </p>
</footer>

        </section>

        <script src="/js/jquery-3.3.1.min.js"></script>
<script src="/js/main.js"></script>
<script src="/js/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>




  
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'your_google_analytics_id', 'auto');
	
	ga('send', 'pageview');
}
</script>





    </body>
</html>
