name: build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "ActionsBuild"
        secrets: 'OctopusServerUrl, OctopusApiKey'
      id: azureSecrets

    - name: Set variables
      shell: pwsh
      run: |
        $basePath = Pwd
        $sitePath = Join-Path $basePath pkg
        $nuspecPath = Join-Path $basePath d4tagirl.com.nuspec

        [xml]$xmlDoc = Get-Content $nuspecPath
        $versionElement = $xmlDoc['package']['metadata']['version']
        $version = [version]$versionElement.InnerText
        $newVersion = [version]"$($version.Major).$($version.Minor).$($env:GITHUB_RUN_NUMBER)"
        $newVersionStr = $newVersion.ToString()

        Write-Host "::set-env name=BASE_PATH::$basePath"
        Write-Host "::set-env name=SITE_PATH::$sitePath"
        Write-Host "::set-env name=VERSION::$newVersionStr"
    - name: Build site
      shell: pwsh
      run: |
        $pwd = pwd
        $uid = sh -c 'id -u'
        $gid = sh -c 'id -g'

        mkdir pkg
        mkdir pkg/prod
        mkdir pkg/dev
        docker run --rm -v "$($pwd):/site" g3rv4/hugo ash -c "hugo --cleanDestinationDir -b https://d4tagirl.com/ -d /site/pkg/prod && chown -R $($uid):$($gid) /site"
        docker run --rm -v "$($pwd):/site" g3rv4/hugo ash -c "hugo --cleanDestinationDir -b https://staging.d4tagirl.com/  -d /site/pkg/staging && chown -R $($uid):$($gid) /site"
    - name: Package it
      shell: pwsh
      run: |
        $basePath = $env:BASE_PATH
        $sitePath = $env:SITE_PATH
        $version = $env:VERSION

        cp "$($basePath)/d4tagirl.com.nuspec" "$($sitePath)/d4tagirl.com.nuspec"

        $nuspecPath = Join-Path $sitePath d4tagirl.com.nuspec

        [xml]$xmlDoc = Get-Content $nuspecPath
        $metadataElement = $xmlDoc['package']['metadata']
        $metadataElement['repository'].SetAttribute("commit", $env:GITHUB_SHA)
        $metadataElement['version'].InnerText = $version
        $xmlDoc.Save($nuspecPath)

        Compress-Archive -Path "$($sitePath)/*" -DestinationPath "$($basePath)/d4tagirl.com.$($version).nupkg"
    - name: Push the package to Octopus, create a release and deploy it
      run: |
        dotnet tool install --global Octopus.DotNet.Cli

        dotnet-octo push --package=$BASE_PATH/d4tagirl.com.$VERSION.nupkg --overwrite-mode=IgnoreIfExists --server=${{ steps.azureSecrets.outputs.OctopusServerUrl }} --apiKey=${{ steps.azureSecrets.outputs.OctopusApiKey }}
        dotnet-octo create-release --project d4tagirl.com --deployto Dev --server "${{ steps.azureSecrets.outputs.OctopusServerUrl }}" --apiKey "${{ steps.azureSecrets.outputs.OctopusApiKey }}" --progress